sudo: required
dist: trusty
services:
- docker
language: python

install: skip

script:
- git clone https://github.com/django/django.git --depth=1
- docker-compose run $COMPOSE_APP

env:
- COMPOSE_APP=sqlite PYTHON_VERSION=3.5
- COMPOSE_APP=sqlite PYTHON_VERSION=3.6
- COMPOSE_APP=sqlite PYTHON_VERSION=3.7
- COMPOSE_APP=postgres PYTHON_VERSION=3.5
- COMPOSE_APP=postgres PYTHON_VERSION=3.6
- COMPOSE_APP=postgres PYTHON_VERSION=3.7
- COMPOSE_APP=mysql PYTHON_VERSION=3.5
- COMPOSE_APP=mysql PYTHON_VERSION=3.6
- COMPOSE_APP=mysql PYTHON_VERSION=3.7
- COMPOSE_APP=mariadb PYTHON_VERSION=3.5
- COMPOSE_APP=mariadb PYTHON_VERSION=3.6
- COMPOSE_APP=mariadb PYTHON_VERSION=3.7
- COMPOSE APP=docs PYTHON_VERSION=3.5
- COMPOSE APP=docs PYTHON_VERSION=3.6
- COMPOSE APP=docs PYTHON_VERSION=3.7