sudo: required
dist: trusty
services:
- docker
language: python
python:
- '3.5'
#- '3.6'
install:
- env
- |
  if [ $COMPOSE_APP == "oracle" ]; then
    wget 'https://github.com/cbandy/travis-oracle/archive/v2.0.3.tar.gz'
    mkdir -p .travis/oracle
    tar x -C .travis/oracle --strip-components=1 -f v2.0.3.tar.gz
    export ORACLE_FILE='instantclient/183000/instantclient-basic-linux.x64-18.3.0.0.0dbru.zip'
    export ORACLE_COOKIE=ic_linuxx8664
    .travis/oracle/download.sh
  fi
script:
- git clone https://github.com/django/django.git --depth=1
- docker-compose run $COMPOSE_APP queries
env:
  matrix:
#  - COMPOSE_APP=sqlite
#  - COMPOSE_APP=postgres
#  - COMPOSE_APP=mysql
#  - COMPOSE_APP=mariadb
  - COMPOSE_APP=oracle
  global:
  - secure: LIW6lYKKTGzces+EaXV0RGk2AgGkCy96HmsfJWYQhXOPLXBmnOVHE1/Slm6L5oAFbdextTaSIa1d8uDr8nzd8DW497MfSlH3jxQfjWTSwV2dcx39ATKumP7XALcOpHI8pwVSPXdDIyGsHA6QipSU7ndrFEnMSDdaMj19Lx2+8k9GI6wQy1AfoZDpKzQFWz4Pu1RKg7oGFynpr9uziIfV9tgOCSQWs5dan+bVQrAOQ4ncHcA0RusiAjmPVML9LHk09UEiJrDTD0HbZqpyEGmcoqbjQL0zFANxRJqAZy+Kylyv+naWCFXYkye72hDx8Pe5daGnQbi19X+S0kjNAu8ik/7cEIw08hG/BXMujelMEzOb4lYSE4XLNdmyXbJqjWLikcYm408FRt0BQwHVzmsuQ4dvL5IWlMq1UodQ4ED0yGQMHQEnIR0xADi+kmot1RGh8HtZwljIMy6lnxJIV1ikEjG2kEKY87QGbD8zTjTduFuQEZv9KZFwpOxbY1XuWZSuKNoZhFSIu7QTQnm31zJ+uSN8CFmKPgyX/4yf3ZODQPuunccEvxozvxyLeZ5qD/U7ANmcaaZXpNg2aQne8W4xWw0svIwr/piT1hpmfS5fbziOTCPcyUr4rWFRnT23D7BCi56wuqm+qcaUkiSptL9YKG6g/FRbiLd3/eTABZH8G1Q=
  - secure: 1NGbkTWqUdH7ydexUD5oc991VFeJmZSGH9sMCeDG9reminYnqXnPSboKs1RZR9WT7VMo/odfn7q+XlQZWj97yBpQO3mt+hLFUPUll7ldfpsexk/74fu81Ut7tqlga5WcORRDQkbQGlE0pHkkZyUVwAn1Ya7kAJGMKebnR1MleiQYHzqOxZGeBDLeTRd+TYO1HLLjeBDGfwg1HAJyshpvwq+TvKmMlxxuPRT9VcKuSn+PkkVQPjA3j/JnS+cHOICxRZh9HgbhoLUHDec2vErZhw54v2vrDRt8arEoWEeHq8z16mJczMLPjoCObisM5rJeWBlotD+49PrPsEtWqaCRY9Ah0g/FMmDC6Q0BtGjzc/Kgq1YVuAHJpJ8+vjYGWdWrB5pMsb9NV7wl9M6lVCbsCaYTNbz6cPPKXmpvcPBta2e/yMewaRHPNI8iH4iss/UDAzkTmHvSMZgHM8A+M6VnSud3V98F4tfFCWshA07A20wJD2J272eGEb4TSh23pmf1mL7A2IpSHhhCadZjcQUSMzbfoGQ9Zc6DImwqifKBBPl28wzImo7SpEWsB2Lcugl+5sq0uyeMEAEXIXfl9XBYZWUrKuglUytwnhwzx2f7cFN0mgXeVFJPNKpunTYGOxjXQqsZmdms4+aH3G307/5xkiAwa0Vc+K/SvAgkkpLZYQI=
