sudo: required
dist: trusty
services:
- docker
language: python
cache: pip

env:
# Linting and docs
- COMPOSE_APP=flake8
- COMPOSE_APP=docs

# Quick Runs. Lowest supported database and Python version.
- COMPOSE_APP=sqlite PYTHON_VERSION=3.5
- COMPOSE_APP=sqlite-gis PYTHON_VERSION=3.5
- COMPOSE_APP=postgres PYTHON_VERSION=3.5 POSTGRES_VERSION=9.4
- COMPOSE_APP=postgres-gis PYTHON_VERSION=3.5 POSTGRES_VERSION=9.4 POSTGIS_VERSION=2.4
- COMPOSE_APP=mysql PYTHON_VERSION=3.5 MYSQL_VERSION=5.6
- COMPOSE_APP=mysql-gis PYTHON_VERSION=3.5 MYSQL_VERSION=5.6
- COMPOSE_APP=mariadb PYTHON_VERSION=3.5 MARIADB_VERSION=10.1

# Sqlite
- COMPOSE_APP=sqlite PYTHON_VERSION=3.6
- COMPOSE_APP=sqlite PYTHON_VERSION=3.7

# Sqlite gis:
- COMPOSE_APP=sqlite-gis PYTHON_VERSION=3.6
- COMPOSE_APP=sqlite-gis PYTHON_VERSION=3.7

# Postgres:
- COMPOSE_APP=postgres PYTHON_VERSION=3.5 POSTGRES_VERSION=9.5
- COMPOSE_APP=postgres PYTHON_VERSION=3.5 POSTGRES_VERSION=9.6
- COMPOSE_APP=postgres PYTHON_VERSION=3.5 POSTGRES_VERSION=10
- COMPOSE_APP=postgres PYTHON_VERSION=3.5 POSTGRES_VERSION=11

- COMPOSE_APP=postgres PYTHON_VERSION=3.6 POSTGRES_VERSION=9.4
- COMPOSE_APP=postgres PYTHON_VERSION=3.6 POSTGRES_VERSION=9.5
- COMPOSE_APP=postgres PYTHON_VERSION=3.6 POSTGRES_VERSION=9.6
- COMPOSE_APP=postgres PYTHON_VERSION=3.6 POSTGRES_VERSION=10
- COMPOSE_APP=postgres PYTHON_VERSION=3.6 POSTGRES_VERSION=11

- COMPOSE_APP=postgres PYTHON_VERSION=3.7 POSTGRES_VERSION=9.4
- COMPOSE_APP=postgres PYTHON_VERSION=3.7 POSTGRES_VERSION=9.5
- COMPOSE_APP=postgres PYTHON_VERSION=3.7 POSTGRES_VERSION=9.6
- COMPOSE_APP=postgres PYTHON_VERSION=3.7 POSTGRES_VERSION=10
- COMPOSE_APP=postgres PYTHON_VERSION=3.7 POSTGRES_VERSION=11

# Postgres gis:
- COMPOSE_APP=postgres-gis PYTHON_VERSION=3.5 POSTGRES_VERSION=9.5 POSTGIS_VERSION=2.4
- COMPOSE_APP=postgres-gis PYTHON_VERSION=3.5 POSTGRES_VERSION=9.6 POSTGIS_VERSION=2.4
- COMPOSE_APP=postgres-gis PYTHON_VERSION=3.5 POSTGRES_VERSION=10 POSTGIS_VERSION=2.4
- COMPOSE_APP=postgres-gis PYTHON_VERSION=3.5 POSTGRES_VERSION=11 POSTGIS_VERSION=2.5

- COMPOSE_APP=postgres-gis PYTHON_VERSION=3.6 POSTGRES_VERSION=9.4 POSTGIS_VERSION=2.4
- COMPOSE_APP=postgres-gis PYTHON_VERSION=3.6 POSTGRES_VERSION=9.5 POSTGIS_VERSION=2.4
- COMPOSE_APP=postgres-gis PYTHON_VERSION=3.6 POSTGRES_VERSION=9.6 POSTGIS_VERSION=2.4
- COMPOSE_APP=postgres-gis PYTHON_VERSION=3.6 POSTGRES_VERSION=10 POSTGIS_VERSION=2.4
- COMPOSE_APP=postgres-gis PYTHON_VERSION=3.6 POSTGRES_VERSION=11 POSTGIS_VERSION=2.5

- COMPOSE_APP=postgres-gis PYTHON_VERSION=3.7 POSTGRES_VERSION=9.4 POSTGIS_VERSION=2.4
- COMPOSE_APP=postgres-gis PYTHON_VERSION=3.7 POSTGRES_VERSION=9.5 POSTGIS_VERSION=2.4
- COMPOSE_APP=postgres-gis PYTHON_VERSION=3.7 POSTGRES_VERSION=9.6 POSTGIS_VERSION=2.4
- COMPOSE_APP=postgres-gis PYTHON_VERSION=3.7 POSTGRES_VERSION=10 POSTGIS_VERSION=2.4
- COMPOSE_APP=postgres-gis PYTHON_VERSION=3.7 POSTGRES_VERSION=11 POSTGIS_VERSION=2.5

# MySQL:
- COMPOSE_APP=mysql PYTHON_VERSION=3.5 MYSQL_VERSION=5.7
- COMPOSE_APP=mysql PYTHON_VERSION=3.5 MYSQL_VERSION=8.0

- COMPOSE_APP=mysql PYTHON_VERSION=3.6 MYSQL_VERSION=5.6
- COMPOSE_APP=mysql PYTHON_VERSION=3.6 MYSQL_VERSION=5.7
- COMPOSE_APP=mysql PYTHON_VERSION=3.6 MYSQL_VERSION=8.0

- COMPOSE_APP=mysql PYTHON_VERSION=3.7 MYSQL_VERSION=5.6
- COMPOSE_APP=mysql PYTHON_VERSION=3.7 MYSQL_VERSION=5.7
- COMPOSE_APP=mysql PYTHON_VERSION=3.7 MYSQL_VERSION=8.0

# MySQL gis:
- COMPOSE_APP=mysql-gis PYTHON_VERSION=3.5 MYSQL_VERSION=5.7
- COMPOSE_APP=mysql-gis PYTHON_VERSION=3.5 MYSQL_VERSION=8.0

- COMPOSE_APP=mysql-gis PYTHON_VERSION=3.6 MYSQL_VERSION=5.6
- COMPOSE_APP=mysql-gis PYTHON_VERSION=3.6 MYSQL_VERSION=5.7
- COMPOSE_APP=mysql-gis PYTHON_VERSION=3.6 MYSQL_VERSION=8.0

- COMPOSE_APP=mysql-gis PYTHON_VERSION=3.7 MYSQL_VERSION=5.6
- COMPOSE_APP=mysql-gis PYTHON_VERSION=3.7 MYSQL_VERSION=5.7
- COMPOSE_APP=mysql-gis PYTHON_VERSION=3.7 MYSQL_VERSION=8.0


# MariaDB:
- COMPOSE_APP=mariadb PYTHON_VERSION=3.5 MARIADB_VERSION=10.2
- COMPOSE_APP=mariadb PYTHON_VERSION=3.5 MARIADB_VERSION=10.3

- COMPOSE_APP=mariadb PYTHON_VERSION=3.6 MARIADB_VERSION=10.1
- COMPOSE_APP=mariadb PYTHON_VERSION=3.6 MARIADB_VERSION=10.2
- COMPOSE_APP=mariadb PYTHON_VERSION=3.6 MARIADB_VERSION=10.3

- COMPOSE_APP=mariadb PYTHON_VERSION=3.7 MARIADB_VERSION=10.1
- COMPOSE_APP=mariadb PYTHON_VERSION=3.7 MARIADB_VERSION=10.2
- COMPOSE_APP=mariadb PYTHON_VERSION=3.7 MARIADB_VERSION=10.3

install:
- sudo pip install docker-compose --upgrade

script:
- git clone https://github.com/django/django.git --depth=1
- docker-compose pull --include-deps $COMPOSE_APP || true
- docker-compose build $COMPOSE_APP
- |
  if [[ $COMPOSE_APP == *-gis ]]; then
    docker-compose run $COMPOSE_APP gis_tests -v2
  else
    docker-compose run $COMPOSE_APP
  fi

after_failure:
  - docker-compose logs $COMPOSE_APP-db || true

deploy:
  provider: script
  script: bash docker_push $COMPOSE_APP
  on:
    branch: master