sudo: required
dist: trusty
services:
- docker
language: python

install: skip

script:
- git clone https://github.com/django/django.git --depth=1
- docker-compose run $COMPOSE_APP

env:
# Sqlite:
- COMPOSE_APP=sqlite PYTHON_VERSION=3.5
- COMPOSE_APP=sqlite PYTHON_VERSION=3.6
- COMPOSE_APP=sqlite PYTHON_VERSION=3.7

# Postgres:
- COMPOSE_APP=postgres PYTHON_VERSION=3.5 POSTGRES_VERSION=9.5
- COMPOSE_APP=postgres PYTHON_VERSION=3.5 POSTGRES_VERSION=9.6

- COMPOSE_APP=postgres PYTHON_VERSION=3.6 POSTGRES_VERSION=9.5
- COMPOSE_APP=postgres PYTHON_VERSION=3.6 POSTGRES_VERSION=9.6

- COMPOSE_APP=postgres PYTHON_VERSION=3.7 POSTGRES_VERSION=9.5
- COMPOSE_APP=postgres PYTHON_VERSION=3.7 POSTGRES_VERSION=9.6

# MySQL:
- COMPOSE_APP=mysql PYTHON_VERSION=3.5 MYSQL_VERSION=5.6
- COMPOSE_APP=mysql PYTHON_VERSION=3.5 MYSQL_VERSION=5.7

- COMPOSE_APP=mysql PYTHON_VERSION=3.6 MYSQL_VERSION=5.6
- COMPOSE_APP=mysql PYTHON_VERSION=3.6 MYSQL_VERSION=5.7

- COMPOSE_APP=mysql PYTHON_VERSION=3.7 MYSQL_VERSION=5.6
- COMPOSE_APP=mysql PYTHON_VERSION=3.7 MYSQL_VERSION=5.7

# MariaDB:
- COMPOSE_APP=mariadb PYTHON_VERSION=3.5 MARIADB_VERSION=10.1
- COMPOSE_APP=mariadb PYTHON_VERSION=3.5 MARIADB_VERSION=10.2
- COMPOSE_APP=mariadb PYTHON_VERSION=3.5 MARIADB_VERSION=10.3

- COMPOSE_APP=mariadb PYTHON_VERSION=3.6 MARIADB_VERSION=10.1
- COMPOSE_APP=mariadb PYTHON_VERSION=3.6 MARIADB_VERSION=10.2
- COMPOSE_APP=mariadb PYTHON_VERSION=3.6 MARIADB_VERSION=10.3

- COMPOSE_APP=mariadb PYTHON_VERSION=3.7 MARIADB_VERSION=10.1
- COMPOSE_APP=mariadb PYTHON_VERSION=3.7 MARIADB_VERSION=10.2
- COMPOSE_APP=mariadb PYTHON_VERSION=3.7 MARIADB_VERSION=10.3

# ToDo: Enable these at some point in the future, once permissions are fixed in volumes
#- COMPOSE_APP=docs PYTHON_VERSION=3.5
#- COMPOSE_APP=docs PYTHON_VERSION=3.6
#- COMPOSE_APP=docs PYTHON_VERSION=3.7