sudo: required
dist: trusty
services:
- docker
language: python
python:
- '3.5'
- '3.6'
script:
- git clone https://github.com/django/django.git --depth=1
- docker-compose run $COMPOSE_APP queries
env:
- COMPOSE_APP=sqlite
- COMPOSE_APP=postgres
- COMPOSE_APP=mysql
- COMPOSE_APP=mariadb
- COMPOSE_APP=oracle
