sudo: required
services:
  - docker
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

env:
  - COMPOSE_APP=sqlite
  - COMPOSE_APP=postgres
  - COMPOSE_APP=mysql
  - COMPOSE_APP=mariadb

script:
  - git clone https://github.com/django/django.git --depth=1
  - docker-compose run $COMPOSE_APP queries