sudo: required
dist: trusty
services:
- docker
language: python
cache: pip
install: skip

stages:
- linting
- test

env:
# Sqlite:
- COMPOSE_APP=sqlite PYTHON_VERSION=3.5
- COMPOSE_APP=sqlite PYTHON_VERSION=3.6
- COMPOSE_APP=sqlite PYTHON_VERSION=3.7

# Sqlite gis:
- COMPOSE_APP=sqlite_gis PYTHON_VERSION=3.5
- COMPOSE_APP=sqlite_gis PYTHON_VERSION=3.6
- COMPOSE_APP=sqlite_gis PYTHON_VERSION=3.7

# Postgres:
- COMPOSE_APP=postgres PYTHON_VERSION=3.5 POSTGRES_VERSION=9.4
- COMPOSE_APP=postgres PYTHON_VERSION=3.5 POSTGRES_VERSION=9.5
- COMPOSE_APP=postgres PYTHON_VERSION=3.5 POSTGRES_VERSION=9.6

- COMPOSE_APP=postgres PYTHON_VERSION=3.6 POSTGRES_VERSION=9.4
- COMPOSE_APP=postgres PYTHON_VERSION=3.6 POSTGRES_VERSION=9.5
- COMPOSE_APP=postgres PYTHON_VERSION=3.6 POSTGRES_VERSION=9.6

- COMPOSE_APP=postgres PYTHON_VERSION=3.7 POSTGRES_VERSION=9.4
- COMPOSE_APP=postgres PYTHON_VERSION=3.7 POSTGRES_VERSION=9.5
- COMPOSE_APP=postgres PYTHON_VERSION=3.7 POSTGRES_VERSION=9.6

# MySQL:
- COMPOSE_APP=mysql PYTHON_VERSION=3.5 MYSQL_VERSION=5.6
- COMPOSE_APP=mysql PYTHON_VERSION=3.5 MYSQL_VERSION=5.7
- COMPOSE_APP=mysql PYTHON_VERSION=3.5 MYSQL_VERSION=8.0

- COMPOSE_APP=mysql PYTHON_VERSION=3.6 MYSQL_VERSION=5.6
- COMPOSE_APP=mysql PYTHON_VERSION=3.6 MYSQL_VERSION=5.7
- COMPOSE_APP=mysql PYTHON_VERSION=3.6 MYSQL_VERSION=8.0

- COMPOSE_APP=mysql PYTHON_VERSION=3.7 MYSQL_VERSION=5.6
- COMPOSE_APP=mysql PYTHON_VERSION=3.7 MYSQL_VERSION=5.7
- COMPOSE_APP=mysql PYTHON_VERSION=3.7 MYSQL_VERSION=8.0

# MariaDB:
- COMPOSE_APP=mariadb PYTHON_VERSION=3.5 MARIADB_VERSION=10.1
- COMPOSE_APP=mariadb PYTHON_VERSION=3.5 MARIADB_VERSION=10.2
- COMPOSE_APP=mariadb PYTHON_VERSION=3.5 MARIADB_VERSION=10.3

- COMPOSE_APP=mariadb PYTHON_VERSION=3.6 MARIADB_VERSION=10.1
- COMPOSE_APP=mariadb PYTHON_VERSION=3.6 MARIADB_VERSION=10.2
- COMPOSE_APP=mariadb PYTHON_VERSION=3.6 MARIADB_VERSION=10.3

- COMPOSE_APP=mariadb PYTHON_VERSION=3.7 MARIADB_VERSION=10.1
- COMPOSE_APP=mariadb PYTHON_VERSION=3.7 MARIADB_VERSION=10.2
- COMPOSE_APP=mariadb PYTHON_VERSION=3.7 MARIADB_VERSION=10.3

matrix:
  include:
  - env: COMPOSE_APP=flake8
    stage: linting
  - env: COMPOSE_APP=docs
    stage: linting

script:
- export PIP_CACHE_VOLUME=$HOME/.cache/pip/
# Ensure the cache directory works with docker. It is extracted with
# the 'travis' user owning it
- sudo chown -R root:root $HOME/.cache/pip/
- git clone https://github.com/django/django.git --depth=1
- |
  if [[ $COMPOSE_APP == *_gis ]]; then
    docker-compose run $COMPOSE_APP gis_tests -v2
  else
    docker-compose run $COMPOSE_APP
  fi
