version: "2.3"
services:
  base:
    build:
      context: .
      args:
        - PYTHON_VERSION=${PYTHON_VERSION:-3.5}
    volumes:
      - ${DJANGO_PATH:-django}:/django
      - ./settings:/django/tests/settings
      - ./entrypoint.sh:/entrypoint.sh
      - /root/.cache/pip/
    working_dir: /django
    entrypoint: /entrypoint.sh python tests/runtests.py
