# ToDo: Refactor this 'extends: sqlite' nonsense out into yaml merging using &.
version: "2.3"

x-base: &base
  build:
    context: .
    args:
    - PYTHON_VERSION=${PYTHON_VERSION}
  volumes:
  - ${DJANGO_PATH}:/django
  - ./settings:/django/tests/settings
  - ./entrypoint.sh:/entrypoint.sh
  - pip-cache:/root/.cache/pip/
  # Using yaml merging here overwrites the arrays. Simpler to just mount this in every service.
  - ./oracle:/oracle
  working_dir: /django
  entrypoint: /entrypoint.sh python tests/runtests.py

services:
  sqlite:
    <<: *base
    environment:
    - DJANGO_SETTINGS_MODULE=settings.test_sqlite
    depends_on:
      memcached:
        condition: service_healthy
      memcached2:
        condition: service_healthy

  postgres:
    <<: *base
    environment:
    - DJANGO_SETTINGS_MODULE=settings.test_postgres
    - EXTRA_REQUIREMENTS=postgres.txt
    depends_on:
      postgres-db:
        condition: service_healthy

  postgres-db:
    image: postgres:${POSTGRES_VERSION}
    environment:
    - POSTGRES_USER=django
    - POSTGRES_PASSWORD=django
    - POSTGRES_DB=django
    volumes:
      - postgres:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "django"]
      interval: 1s
      timeout: 3s
      retries: 30

  mysql:
    <<: *base
    environment:
    - DJANGO_SETTINGS_MODULE=settings.test_mysql
    - EXTRA_REQUIREMENTS=mysql.txt
    depends_on:
    - mysql-db
  mysql-db:
    image: mysql:${MYSQL_VERSION}
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    volumes:
      - mysql:/var/lib/mysql
    environment:
    - MYSQL_USER=django
    - MYSQL_PASSWORD=django
    - MYSQL_DATABASE=django
    - MYSQL_ALLOW_EMPTY_PASSWORD=1

  mariadb:
    <<: *base
    environment:
    - DJANGO_SETTINGS_MODULE=settings.test_mariadb
    - EXTRA_REQUIREMENTS=mysql.txt
    depends_on:
    - mariadb-db
  mariadb-db:
    image: mariadb:${MARIADB_VERSION}
    volumes:
    - mariadb:/var/lib/mysql
    environment:
    - MYSQL_USER=django
    - MYSQL_PASSWORD=django
    - MYSQL_DATABASE=django
    - MYSQL_ALLOW_EMPTY_PASSWORD=1

  oracle:
    <<: *base
    environment:
    - DJANGO_SETTINGS_MODULE=settings.test_oracle
    - EXTRA_REQUIREMENTS=oracle.txt
    depends_on:
      oracle-db:
        condition: service_healthy
  oracle-db:
    image: sath89/oracle-12c
    volumes:
      - oracle:/u01/app/oracle/
    environment:
      - WEB_CONSOLE=false
    healthcheck:
      test: echo "select * from v\xe;" | sqlplus -S sys/oracle as sysdba || exit 1
      timeout: 3s
      interval: 30s
      retries: 30

  # There are issues running the tests with 1 memcached server in parallel.
  # For now use two.
  memcached:
    image: memcached:1.5-alpine
    healthcheck:
      test: /usr/bin/nc -z 127.0.0.1 11211 || exit 1
      timeout: 1s
      interval: 30s
      retries: 10

  memcached2:
    image: memcached:1.5-alpine
    healthcheck:
      test: /usr/bin/nc -z 127.0.0.1 11211 || exit 1
      timeout: 1s
      interval: 30s
      retries: 10

  docs:
    <<: *base
    volumes:
      - ./docs-requirements.txt:/django/tests/requirements/docs.txt
    environment:
      - EXTRA_REQUIREMENTS=docs.txt
    entrypoint: /entrypoint.sh
    command: bash -c "cd docs && make spelling"

volumes:
  pip-cache:
  oracle:
  mysql:
  mariadb:
  postgres: