version: "2.3"
services:
  django:
    container_name: django-postgres
    environment:
      - DJANGO_SETTINGS_MODULE=settings.test_postgres
      - EXTRA_REQUIREMENTS=postgres.txt
    extends:
      file: base.yml
      service: base
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:${POSTGRES_VERSION:-9.6}
#    volumes:
#      - ./databases/postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh
    environment:
    - POSTGRES_USER=django
    - POSTGRES_PASSWORD=django
    - POSTGRES_DB=django
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "django"]
      interval: 1s
      timeout: 3s
      retries: 30
